language: node_js
node_js:
- 12.16.3
deploy:
  provider: heroku
  api_key:
    secure: wnmifAj3qJU6WAk8kLqoSTCjrkjs2auTEhmpYEe137MSLtdVBbh6tcBpxhS6ePQDVk4iCi68rtPthW2IJDSFeiXx4p+7DP9lsmC6qd+gAoeb3rRyxRjqxrRNRzHydi9Er/KROYVLxQxB8BzBS6SMsUecFnhQVEjkB+5ZNhbJNCgUj0jnvvSRNYufnsoR+EVdyUHAm9ANrnXfIrrbKkkn9KmNPzs31hZAhp+wA2oj7uWfcwzr1sjVjmW2EvcijD+NQZD1Z+VIcao3GEwOBedeaAJ77lEx0KaHbDQb1T6yyaBL9rzgo9GgUCwIaBTgOsxzxOhePomD5LPvzSaJOzaXyZcxolkUxPPV9DHomHSZ1QeM1suiEI/lK1GTbioX2/i+INeRxXubLWPtN0fM0wZehBYC+gz7WNze9DZH/xdvjMNCmUJQ7SD483D9ThdkTcPkICrqxNNrGag0+U3t0PqwuQUmcEKGEa/bKS8Bch1MITyRRmQQON/C9aov6PQ2rXMkX6irFDcHk6/9GNNe+acbuv1JNdWniis33LFyys/uQHIeQCfMdDObRA/TwU1ZKHElI1RbCOUj8fqg/9E4+SdFzx4jgsocPXVYfDcRQVKG2Pqylful25TzVeZTJhez0Aj0p406bcKpnjBPmiO5rXAGrrpi3JFg75f3o7N/DvOHzWM=
  app: evening-sands-23391
  on:
    repo: micaiah-effiong/visitation-tracker
  skip_cleanup: 'true'
env:
  global:
    secure: WqSs2XJ1fCcS5bPYBEaLH8kZ0fOjvk5i8o5hngi99PB4OUTajjaBDeKy3GRol3a/Qrso5GAcruoKEu0EimlL5RKa1vM1c9OdxnP/nA2N+RYsQnVgyFZT5cM8vur6WZ7webhUnizjJMAHcnfXhBAOEVmqNlnLMcaPZvZnBZZURIIP/tn5Th41PgVJcbYBfKZ0/nCsHp8NgSRz4lOyfYbLh4WY8wcefFJz0sCWwvLcBmfk2BuvGj1ID4/DY1+xQibDmEkivbhEolsnw1vcW6STaJoHKsFivZwo04HqJmHHeWBsNUZY4f2BEua8Ywg9Ah6FwiLsas1NrLa/W7Q2AlmIPk4IPkDUX5Y4BQ9HNu/vJ9tNqxJ30Klb1O60X8ay7CwdsYKAATluj/BfHlmrTpG3Vmis3ieYkY9gyga0fMR0fKzD/4nnwlwjMLPkWVT5yF6s5tO4BmoUQwbpbFVImZ5SF2DjW/nQpIEsbFoy5ko1cqsbmEbjyOFgplYltAk9/msJQlNlMCLemfrJmFdqY8XQmi2i7ArJadaJcZPVtvZTCxR/cJ0jmdTIlkLqxxwLChkJU4jGdrRTI5dWvcTV9C5DXu7ipB6x+FdCEZNmzQM153DYI4D+HBKHlx68aPYdICKXvouxbtDSwiPMGCPvOgppA0unN+9VHq1T+D02KDKyNFg=
